try{
    hello();
}catch(err){
console.log(err);//error por la funci√≥n
}